language: groovy
branches:
  only:
  - master
  - develop
  - 1.1.0
env:
  global:
  - secure: TayEP5vUCUMB9RWOai2vvgyMkiZwEBfUG/lluEJCO01uTjLDvT46G7HtCKbV4IXL1oALtVXpiGvWc9BVPAafLyAcq3DU4wCt3ETadInTYhs+xQFDK7xc9shF58KSQKwwPRdzY2z4FWt/BrylauBwQf0fCMZN1ioPD0MdLaBCe1w=
  - secure: Q8KvVcyZKN4ikBArY8KNL3GGH+CdFj4bD4XSRr4ZMplWJwR2pp6qsnfaH09ZQbThZikyWXLgL03aLJhyObjtY42QKBXMkyR++1dEpXaY+AWWJ+fRHu7gA05KYTcAFzaaPBcsp31zLpqclu7Md7HzgolGEi6YlZveK02ogEGHufo=
  - secure: hzYbi3GDszq0rbpSCeai0tU8Xcu4VLLnPQjU7qbli+Y80yvBSasB7LCZC3rVs1RL6olFl1lAhbF4DbnUszDiq0wWpwZDD9Dqt1oPrqfUpsgt1spQmpjnlw3F6jXH22JlwkNDr+pBobuc2TN6iPQRE+ziku6pQaYKAIVUV4UQZN4=
  - secure: LU8pcBzayf+SzNjIooom+S8ygAu6oIR+vb0UQQrnU8sAOzkwF6BXKN9ekKGDZ4Mvmufr6GCSwh9zrsnt6MAu52NmOvB4eMfb+6L103vapylJJERxgMrI8YZJ/4ks25yvlaM/37mNGP4Xv60QLykGmY9SGT6VOdJvzIWPCelK2uE=
  - secure: Lq7BGqu3QgOzzuLScNB7Tlyz0Pr5NizUScDXgAd6OpuP6PsAoeoZOUkS+geHMmAXyH7l5JygIZzbGuOMQIOrN0hrCcRtGiIxclHYXHRjN8Podzdg8hRXNncjAg5zp2pqkeRTLNs08ZJTL5SON4PazVLbCZ7dYasvA0INQ5O2b1Y=
  - secure: bAJW+nMfMCJ5cvVn1HtWCqI+AhLGnHuUx5ss6hyhm4L/Jd36cctLSNWv9FrpF2Eq/8r1J/RT/2mxm6b5nByBEaIzo+F1wc8+SNPTa0c+odjbTNTP9ViYtKP+JEKvgLfclW0asiae7TtffyjeXQJdKWdRIgGxpq2+/Kcr7jnRq9Y=
before_install:
- chmod a+x ./deploy.sh
script:
- mvn clean test --settings settings.xml
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ] ; then ./deploy.sh ; fi
