language: java
branches:
  only:
  - develop
  - master
  - "/release.*/"
env:
  global:
  - secure: UWkJueXpx/ibE29FPUQm4QaksioKyDEBCYvYtzGArwzZNUvM/859sx9reQ+6tZ3yhR0RdojuXfHd7jDi7Sbn0AoZyQX+qJdZ/OoB9JVU0Q4FOH4UfyC5LZayUXjfXyrS0b2CNF5M0i0Xsgm5X6AydNwcetORLdnwOLcgPrI2Ffc=
  - secure: f0QkVGRW2rCVwrzvZ1YIEBidEwdjJlGAO8g66S+GCfdEBBIbniRQ6UPbjIwf+x58w20ruiC9N7VpeVLt1M9+GbfhSccwuggwMG/hA5ZalTV2zxWy13fyxPxb4id3RvgRL9JoM9K4qCyzWOR/d+ud7IE3f6dVRVIqhrzkxxOzOd8=
  - secure: Gc9exYH1HPZc84t7e6K97aUVpHql8IdEEoIfCpa49Z4fi4WZoPERzkX4R0noZu6B5y49xcD4GiH27qSCdOSTNJqQ7kLBZ3o5bcGuiv+pTThu7mxq5vC6wOAOhprd3OSNLRQG2hLM291q6hS8wxJOoHNf1TTu2ZtqGXXVYUGhkkY=
  - secure: XMr5Tfyh6wJmB/Avf21ptZ+Gl/wo4kZIkdvmgrEpjsfAbh/GHjIHiF69Eg5dOxRjN/MnDM4cfWOEE5v3vD9J1nLgra7GSM5Km+oR8I705C2ZmCnGGpl9iTBDTPJVIx6zOJjcZVOY1GhNacl1tw3BtaqPpFDR9O2coLUqR9CIRKI=
  - secure: UMzgXB9fYjpFQdzCzICW5qiK5H+0jc7qJsw3Bwj51ErD3zTlzEZTu/qOsOMxaAA9AIVEJ4FVMPNuiiSBzTfzOJKn48oFIy3EkyfgSPzHpf8EqW5hKSge6/b/nSLq7vuN385gBcB4plup9SoDU3V44jW5/90s03Vdh5jrZnP4Wgw=
  - secure: X8xWr8cBFQh3FAN/7/0gql/MTAH3ACGSSpWJGhp482CvjqgMapzhb8OrfZ3NIdTLenb+M7MDEHk3FYhSFXy4Hv/qbDGJDFS3mYY6sS3idVlrC/XiMBJDD4sIMsBXGg8P/pXze+7rIudJ+abCjRjsoqAaoV/JZSIq4sqRfRRb+WA=
stages:
- name: Unit Tests
  if: branch = develop
- name: Staging
  if: branch =~ ^release
- name: Master
  if: branch = master
jobs:
  include:
  - stage: Unit Tests
    install: mvn --settings settings.xml -DskipTests=true -Dmaven.javadoc.skip=true
      -Pdevelop -B -V install
    script: mvn --settings settings.xml -Pdevelop clean test
  - stage: Staging
    before-install: chmod +x ./deploy.sh
    install: mvn --settings settings.xml -DskipTests=true -Dmaven.javadoc.skip=true
      -Pstaging -B -V install
    script: mvn --settings settings.xml -Dmaven.javadoc.skip=true -Pstaging -B -V
      clean test
    after_success: ./deploy.sh
  - stage: Master
    install: mvn --settings settings.xml -DskipTests=true -Dmaven.javadoc.skip=true
      -B -V install
    script: mvn --settings settings.xml clean test site
